CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE lifecycle_status AS ENUM ('ACTIVE','INACTIVE','ARCHIVED');
CREATE TYPE resource_type AS ENUM ('APPLICATION','MODULE','PAGE','UI_COMPONENT','BUSINESS_RESOURCE','EXTERNAL_RESOURCE');
CREATE TYPE subject_type AS ENUM ('USER','GROUP','ROLE');
CREATE TYPE sync_status AS ENUM ('PENDING','APPLIED','FAILED','REVOKING','DRIFTED');

CREATE TABLE app_user (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), issuer varchar(255) NOT NULL, external_id varchar(255) NOT NULL, username varchar(255) NOT NULL, display_name varchar(255), email varchar(320), status lifecycle_status NOT NULL DEFAULT 'ACTIVE', version bigint NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(issuer,external_id));
CREATE TABLE directory_group (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), issuer varchar(255) NOT NULL, external_id varchar(255) NOT NULL, normalized_path varchar(1024) NOT NULL, display_name varchar(255) NOT NULL, parent_id uuid REFERENCES directory_group(id) ON DELETE RESTRICT, status lifecycle_status NOT NULL DEFAULT 'ACTIVE', sync_at timestamptz, version bigint NOT NULL DEFAULT 0, UNIQUE(issuer,external_id), UNIQUE(issuer,normalized_path));
CREATE TABLE user_group_membership (user_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE, group_id uuid NOT NULL REFERENCES directory_group(id) ON DELETE CASCADE, synchronized_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_id,group_id));
CREATE TABLE application_role (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), role_key varchar(160) NOT NULL UNIQUE, name_fa varchar(255) NOT NULL, name_en varchar(255) NOT NULL, status lifecycle_status NOT NULL DEFAULT 'ACTIVE', version bigint NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE user_role_assignment (user_id uuid NOT NULL REFERENCES app_user(id) ON DELETE RESTRICT, role_id uuid NOT NULL REFERENCES application_role(id) ON DELETE RESTRICT, expires_at timestamptz, PRIMARY KEY(user_id,role_id));
CREATE TABLE group_role_assignment (group_id uuid NOT NULL REFERENCES directory_group(id) ON DELETE RESTRICT, role_id uuid NOT NULL REFERENCES application_role(id) ON DELETE RESTRICT, expires_at timestamptz, PRIMARY KEY(group_id,role_id));

CREATE TABLE panel (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code varchar(100) NOT NULL UNIQUE, name_fa varchar(255) NOT NULL UNIQUE, name_en varchar(255) NOT NULL UNIQUE, slug varchar(100) NOT NULL UNIQUE, remote_entry_path varchar(500) NOT NULL, exposed_module varchar(160) NOT NULL, route_base_path varchar(255) NOT NULL UNIQUE, icon varchar(100), semantic_version varchar(50) NOT NULL, contract_version varchar(50) NOT NULL, integrity varchar(255), health_check_url varchar(500), active boolean NOT NULL DEFAULT false, sort_order integer NOT NULL DEFAULT 0, version bigint NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE service_target (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), target_key varchar(100) NOT NULL UNIQUE, base_url varchar(500) NOT NULL, mtls_secret_ref varchar(255), active boolean NOT NULL DEFAULT true, connect_timeout_ms integer NOT NULL DEFAULT 3000, response_timeout_ms integer NOT NULL DEFAULT 10000, max_response_bytes bigint NOT NULL DEFAULT 10485760);
CREATE TABLE proxy_route (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), route_key varchar(120) NOT NULL UNIQUE, path_prefix varchar(500) NOT NULL UNIQUE, target_id uuid NOT NULL REFERENCES service_target(id) ON DELETE RESTRICT, strip_prefix integer NOT NULL DEFAULT 0, active boolean NOT NULL DEFAULT true, version bigint NOT NULL DEFAULT 0, CHECK(path_prefix LIKE '/%'), CHECK(path_prefix NOT LIKE '%..%'));

CREATE TABLE resource (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), resource_key varchar(500) NOT NULL UNIQUE, type resource_type NOT NULL, parent_id uuid REFERENCES resource(id) ON DELETE RESTRICT, name_fa varchar(255) NOT NULL, name_en varchar(255) NOT NULL, owner_domain varchar(160), classification varchar(80), external_system varchar(100), external_type varchar(100), external_id varchar(255), status lifecycle_status NOT NULL DEFAULT 'ACTIVE', version bigint NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(external_system,external_type,external_id));
CREATE TABLE action (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), action_key varchar(100) NOT NULL UNIQUE, name_fa varchar(255) NOT NULL, name_en varchar(255) NOT NULL);
CREATE TABLE resource_action (resource_id uuid NOT NULL REFERENCES resource(id) ON DELETE RESTRICT, action_id uuid NOT NULL REFERENCES action(id) ON DELETE RESTRICT, PRIMARY KEY(resource_id,action_id));
CREATE TABLE route_operation (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), route_id uuid NOT NULL REFERENCES proxy_route(id) ON DELETE CASCADE, http_method varchar(12) NOT NULL, relative_pattern varchar(500) NOT NULL, resource_id uuid NOT NULL REFERENCES resource(id) ON DELETE RESTRICT, action_id uuid NOT NULL REFERENCES action(id) ON DELETE RESTRICT, max_body_bytes bigint NOT NULL DEFAULT 1048576, UNIQUE(route_id,http_method,relative_pattern));
CREATE TABLE authorization_grant (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), subject_type subject_type NOT NULL, subject_id uuid NOT NULL, resource_id uuid NOT NULL REFERENCES resource(id) ON DELETE RESTRICT, action_id uuid NOT NULL REFERENCES action(id) ON DELETE RESTRICT, relation varchar(100) NOT NULL, condition_id uuid, expires_at timestamptz, status lifecycle_status NOT NULL DEFAULT 'ACTIVE', version bigint NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX authorization_grant_lookup_idx ON authorization_grant(subject_type,subject_id,resource_id,action_id) WHERE status='ACTIVE';
CREATE TABLE condition_definition (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), condition_key varchar(160) NOT NULL UNIQUE, expression jsonb NOT NULL, compiled_version varchar(50) NOT NULL, active boolean NOT NULL DEFAULT true, version bigint NOT NULL DEFAULT 0);
ALTER TABLE authorization_grant ADD CONSTRAINT authorization_grant_condition_fk FOREIGN KEY(condition_id) REFERENCES condition_definition(id) ON DELETE RESTRICT;
CREATE TABLE data_policy (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), policy_key varchar(160) NOT NULL UNIQUE, resource_id uuid NOT NULL REFERENCES resource(id) ON DELETE RESTRICT, action_id uuid NOT NULL REFERENCES action(id) ON DELETE RESTRICT, condition_id uuid REFERENCES condition_definition(id) ON DELETE RESTRICT, obligations jsonb NOT NULL, active boolean NOT NULL DEFAULT true, version bigint NOT NULL DEFAULT 0);

CREATE TABLE superset_asset (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), resource_id uuid NOT NULL UNIQUE REFERENCES resource(id) ON DELETE RESTRICT, external_id varchar(255) NOT NULL UNIQUE, asset_type varchar(40) NOT NULL, title varchar(500) NOT NULL, url_path varchar(1000) NOT NULL, owner_external_id varchar(255), published boolean NOT NULL DEFAULT false, tags jsonb NOT NULL DEFAULT '[]', last_synced_version varchar(100), synchronized_at timestamptz);
CREATE TABLE superset_subject_mapping (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), subject_type subject_type NOT NULL, subject_id uuid NOT NULL, superset_subject_type varchar(40) NOT NULL, superset_subject_id varchar(255) NOT NULL, UNIQUE(subject_type,subject_id));
CREATE TABLE superset_access_sync (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), grant_id uuid NOT NULL REFERENCES authorization_grant(id) ON DELETE RESTRICT, status sync_status NOT NULL DEFAULT 'PENDING', idempotency_key varchar(255) NOT NULL UNIQUE, attempts integer NOT NULL DEFAULT 0, last_error varchar(1000), updated_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE authorization_decision_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), decision_id varchar(100) NOT NULL UNIQUE, subject_key varchar(500) NOT NULL, resource_key varchar(500) NOT NULL, action_key varchar(100) NOT NULL, result varchar(20) NOT NULL, reason_code varchar(100) NOT NULL, model_version varchar(100), correlation_id varchar(100) NOT NULL, safe_context_hash varchar(128), decided_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX authorization_decision_lookup_idx ON authorization_decision_log(subject_key,resource_key,action_key,decided_at DESC);
CREATE TABLE audit_event (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_key varchar(500) NOT NULL, event_type varchar(160) NOT NULL, target_type varchar(100) NOT NULL, target_key varchar(500) NOT NULL, correlation_id varchar(100) NOT NULL, safe_details jsonb NOT NULL DEFAULT '{}', occurred_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE outbox_event (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), aggregate_type varchar(100) NOT NULL, aggregate_id uuid NOT NULL, event_type varchar(160) NOT NULL, payload jsonb NOT NULL, idempotency_key varchar(255) NOT NULL UNIQUE, attempts integer NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(), processed_at timestamptz, last_error varchar(1000), created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX outbox_pending_idx ON outbox_event(available_at) WHERE processed_at IS NULL;
CREATE TABLE schema_version (component varchar(100) PRIMARY KEY, version varchar(100) NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
