package com.aurevia.authz.outbound;
import static com.aurevia.authz.outbound.OutboundModels.*;
import com.aurevia.authz.observability.AuditTrail;
import java.net.URI;import java.util.*;import java.util.regex.Pattern;
import org.springframework.dao.OptimisticLockingFailureException;import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
@Service public class OutboundRegistryService {
 private static final Pattern CONNECTION_REF=Pattern.compile("^connection://[a-zA-Z0-9._/-]+$");
 private static final Set<String> MODES=Set.of("FORWARD_USER_TOKEN","LEGACY_SERVICE_TOKEN");
 private static final Set<String> FORMATS=Set.of("FORM_URLENCODED","JSON","HTTP_BASIC","OAUTH_CLIENT_CREDENTIALS");
 private static final Set<String> TRANSPORTS=Set.of("USER_AUTHORIZATION_HEADER","INTERNAL_LEGACY_HEADER");
 private final OutboundRegistryRepository repository;private final AuditTrail audit;
 public OutboundRegistryService(OutboundRegistryRepository repository,AuditTrail audit){this.repository=repository;this.audit=audit;}
 public List<ConnectionView> connections(){return repository.connections();}
 public RuntimeConnectionView runtimeConnection(String reference){return repository.runtimeConnection(connectionReference(reference)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Approved outbound connection not found"));}
 @Transactional public MutationResult createConnection(ConnectionCommand command,String actor){String origin=connectionOrigin(command);UUID id=UUID.randomUUID();repository.createConnection(id,command,origin,actor);audit.success("OUTBOUND_AUTH","connection.created",actor,null,"OUTBOUND_CONNECTION",id.toString(),command.connectionRef(),"CREATE",null,Map.of("tlsRequired",command.tlsRequired()));return new MutationResult(id,0);}
 @Transactional public MutationResult updateConnection(UUID id,ConnectionCommand command,String actor){String origin=connectionOrigin(command);if(repository.updateConnection(id,command,origin,actor)!=1)throw new OptimisticLockingFailureException("VERSION_CONFLICT");audit.success("OUTBOUND_AUTH","connection.updated",actor,null,"OUTBOUND_CONNECTION",id.toString(),command.connectionRef(),"UPDATE",null,Map.of("tlsRequired",command.tlsRequired()));return new MutationResult(id,command.version()+1);}
 public List<ProfileView> profiles(String search){return repository.profiles(limit(search==null?"":search,100));}
 public ProfileView profile(UUID id){return repository.profile(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Outbound profile not found"));}
 public RuntimeProfileView runtimeProfile(UUID id){return repository.runtimeProfile(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Active outbound profile not found"));}
 public List<UsageView> usage(UUID id){profile(id);return repository.usage(id);}
 @Transactional public ProfileView createProfile(ProfileCommand raw,String actor){ProfileCommand command=normalize(raw);UUID id=UUID.randomUUID();repository.createProfile(id,command,actor);audit.success("OUTBOUND_AUTH","auth.profile.created",null,null,"OUTBOUND_AUTH_PROFILE",id.toString(),command.code(),"CREATE",null,safe(command));return profile(id);}
 @Transactional public ProfileView updateProfile(UUID id,long version,ProfileCommand raw,String actor){ProfileCommand command=normalize(raw);ProfileView before=profile(id);if(repository.updateProfile(id,version,command,actor)!=1)throw new OptimisticLockingFailureException("VERSION_CONFLICT");ProfileView after=profile(id);audit.success("OUTBOUND_AUTH","auth.profile.updated",null,null,"OUTBOUND_AUTH_PROFILE",id.toString(),command.code(),"UPDATE",safe(before),safe(after));return after;}
 @Transactional public ProfileView updateProfileStatus(UUID id,long version,boolean active,String actor){if(repository.updateProfileStatus(id,version,active,actor)!=1)throw new OptimisticLockingFailureException("VERSION_CONFLICT");audit.success("OUTBOUND_AUTH",active?"auth.profile.activated":"auth.profile.deactivated",null,null,"OUTBOUND_AUTH_PROFILE",id.toString(),id.toString(),"STATUS",null,Map.of("active",active));return profile(id);}
 private static String connectionOrigin(ConnectionCommand c){String ref=connectionReference(c.connectionRef());if(c.name()==null||c.name().isBlank())throw new IllegalArgumentException("Connection name is required");URI uri;try{uri=URI.create(c.baseUrl().trim()).normalize();}catch(RuntimeException e){throw new IllegalArgumentException("Invalid connection URL",e);}if(!Set.of("http","https").contains(uri.getScheme())||uri.getHost()==null||uri.getUserInfo()!=null||uri.getQuery()!=null||uri.getFragment()!=null||!(uri.getPath().isEmpty()||"/".equals(uri.getPath())))throw new IllegalArgumentException("Connection URL must be an HTTP(S) origin");if(c.tlsRequired()&&!"https".equals(uri.getScheme()))throw new IllegalArgumentException("TLS-required connection must use HTTPS");return uri.getScheme()+"://"+uri.getHost()+(uri.getPort()<0?"":":"+uri.getPort());}
 private static ProfileCommand normalize(ProfileCommand p){String mode=upper(p.authMode(),50),format=upper(p.requestFormat(),50),transport=upper(p.credentialTransport(),50);if(!MODES.contains(mode)||!FORMATS.contains(format)||!TRANSPORTS.contains(transport))throw new IllegalArgumentException("Unsupported outbound authentication option");String connection=reference(p.tokenConnectionRef(),"connection://"),endpoint=endpoint(p.tokenEndpointPath()),secret=reference(p.credentialSecretRef(),"secret://");if("LEGACY_SERVICE_TOKEN".equals(mode)&&(connection.isEmpty()||endpoint.isEmpty()||secret.isEmpty()||!"INTERNAL_LEGACY_HEADER".equals(transport)))throw new IllegalArgumentException("Legacy profiles require connection, endpoint path, secret reference, and internal transport");return new ProfileCommand(code(p.code()),limit(p.name(),255),nullable(p.description(),1000),mode,connection,endpoint,format,secret,nullable(p.scope(),1000),nullable(p.audience(),1000),pointer(p.tokenResponsePointer()),pointer(p.expiresInResponsePointer()),pointer(p.tokenTypeResponsePointer()),scheme(p.authorizationScheme()),transport,p.expirySkewSeconds(),p.connectTimeoutMs(),p.responseTimeoutMs(),p.maxTokenResponseSize(),p.active());}
 private static String connectionReference(String v){String s=v==null?"":v.trim();if(!CONNECTION_REF.matcher(s).matches())throw new IllegalArgumentException("Invalid connection reference");return s;}
 private static String endpoint(String v){String s=nullable(v,1000);if(s.isEmpty())return s;if(!s.startsWith("/")||s.contains("://")||s.contains("..")||s.contains("%")||s.contains("\\")||s.contains("?")||s.contains("#")||s.contains("//"))throw new IllegalArgumentException("Invalid token endpoint path");return s;}
 private static String pointer(String v){String s=limit(v,255);if(!s.matches("/(?:[A-Za-z0-9_-]+)(?:/(?:[A-Za-z0-9_-]+))*"))throw new IllegalArgumentException("Invalid JSON pointer");return s;}
 private static String reference(String v,String prefix){String s=nullable(v,1000);if(s.isEmpty())return s;if(!s.startsWith(prefix)||!s.matches("[A-Za-z]+://[A-Za-z0-9._/-]+"))throw new IllegalArgumentException("Invalid secret or connection reference");return s;}
 private static String scheme(String v){String s=limit(v,40);if(!s.matches("[A-Za-z][A-Za-z0-9_-]*"))throw new IllegalArgumentException("Invalid authorization scheme");return s;}
 private static String code(String v){String s=limit(v,160);if(!s.matches("[A-Za-z][A-Za-z0-9._-]*"))throw new IllegalArgumentException("Invalid profile code");return s;}
 private static String upper(String v,int n){return limit(v,n).toUpperCase(Locale.ROOT);}private static String nullable(String v,int n){return v==null?"":limit(v,n);}private static String limit(String v,int n){if(v==null||v.length()>n)throw new IllegalArgumentException("Invalid field length");return v.trim();}
 private static Map<String,Object> safe(ProfileCommand p){return Map.of("code",p.code(),"authMode",p.authMode(),"tokenConnectionRef",p.tokenConnectionRef(),"credentialSecretRef",p.credentialSecretRef(),"active",p.active());}
 private static Map<String,Object> safe(ProfileView p){return Map.of("code",p.code(),"authMode",p.authMode(),"tokenConnectionRef",String.valueOf(p.tokenConnectionRef()),"credentialSecretRef",String.valueOf(p.credentialSecretRef()),"version",p.version());}
}
