import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Alert,Button,Card,Checkbox,Form,Input,InputNumber,Modal,Popconfirm,Select,Space,Table,Tabs,Tag,Tree,Typography,message}from'antd';import type{RemoteContext,RemoteModule}from'@aurevia/contracts';
import { SupersetAssets } from './SupersetAssets';
import { PanelsView } from './Panels';
import { AccessStudio } from './AccessStudio';
import { LogsView } from './Logs';
import { ProxyRouteManagement } from './ProxyRoutes';
import { OutboundAuthProfiles } from './OutboundAuthProfiles';
export const contractVersion='1' as const;type Row=Record<string,any>;let csrf:{headerName:string;token:string}|undefined;
async function api(path:string,init:RequestInit={}){const method=init.method??'GET',headers:Record<string,string>={'Content-Type':'application/json',...(init.headers as Record<string,string>??{})};if(method!=='GET'){const token=csrf??await fetch('/api/v1/csrf',{credentials:'same-origin'}).then(r=>r.json());csrf=token;headers[token.headerName]=token.token}const r=await fetch('/api/v1/admin'+path,{...init,headers,credentials:'same-origin'});if(!r.ok)throw new Error((await r.text())||`HTTP ${r.status}`);return r.status===204?undefined:r.json()}const required=[{required:true,message:'این فیلد الزامی است'}];
const normalizeResources=(rows:Row[])=>rows.map(r=>({...r,actions:JSON.parse(r.actions_json??'[]')}));
function Panels(){const[rows,setRows]=useState<Row[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<Row>(),[form]=Form.useForm();const load=()=>api('/panels').then(setRows).catch(e=>message.error(e.message));useEffect(()=>{void load()},[]);const save=async(v:Row)=>{try{const body={code:v.code,nameFa:v.name_fa,nameEn:v.name_en,slug:v.slug,remoteEntry:v.remote_entry_path,exposedModule:v.exposed_module,routeBasePath:v.route_base_path,semanticVersion:v.semantic_version,contractVersion:v.contract_version,integrity:v.integrity||null,active:v.active??true,sortOrder:v.sort_order??0};await api(editing?`/panels/${editing.id}?version=${editing.version}`:'/panels',{method:editing?'PUT':'POST',body:JSON.stringify(body)});message.success('میکروفرانت ذخیره شد');setOpen(false);load()}catch(e){message.error((e as Error).message)}};const show=(r?:Row)=>{setEditing(r);form.setFieldsValue(r??{active:true,semantic_version:'0.1.0',contract_version:'1',exposed_module:'./bootstrap',sort_order:50});setOpen(true)};return <Card title="مدیریت میکروفرانت‌ها" extra={<Button type="primary" onClick={()=>show()}>میکرو جدید</Button>}><Table rowKey="id" dataSource={rows} pagination={false} columns={[{title:'کد',dataIndex:'code'},{title:'نام',dataIndex:'name_fa'},{title:'مسیر',dataIndex:'route_base_path'},{title:'Remote Entry',dataIndex:'remote_entry_path'},{title:'وضعیت',render:(_,r)=><Tag color={r.active?'green':'default'}>{r.active?'فعال':'غیرفعال'}</Tag>},{title:'عملیات',render:(_,r)=><Space><Button onClick={()=>show(r)}>ویرایش</Button><Popconfirm title="غیرفعال شود؟" onConfirm={()=>api(`/panels/${r.id}?version=${r.version}`,{method:'DELETE'}).then(load)}><Button danger>غیرفعال</Button></Popconfirm></Space>}]}/><Modal open={open} title={editing?'ویرایش میکروفرانت':'تعریف میکروفرانت'} onCancel={()=>setOpen(false)} onOk={()=>form.submit()} width={760}><Form form={form} layout="vertical" onFinish={save}><Space wrap align="start"><Form.Item name="code" label="کد" rules={required}><Input/></Form.Item><Form.Item name="slug" label="Slug" rules={required}><Input/></Form.Item><Form.Item name="name_fa" label="نام فارسی" rules={required}><Input/></Form.Item><Form.Item name="name_en" label="نام انگلیسی" rules={required}><Input/></Form.Item><Form.Item name="remote_entry_path" label="Remote Entry" rules={required}><Input style={{width:300}}/></Form.Item><Form.Item name="exposed_module" label="Exposed Module" rules={required}><Input/></Form.Item><Form.Item name="route_base_path" label="مسیر پایه" rules={required}><Input/></Form.Item><Form.Item name="semantic_version" label="نسخه" rules={required}><Input/></Form.Item><Form.Item name="contract_version" label="نسخه قرارداد" rules={required}><Input/></Form.Item><Form.Item name="sort_order" label="ترتیب"><InputNumber/></Form.Item><Form.Item name="active" valuePropName="checked"><Checkbox>فعال</Checkbox></Form.Item></Space></Form></Modal></Card>}
function Resources(){const[rows,setRows]=useState<Row[]>([]),[actions,setActions]=useState<Row[]>([]),[open,setOpen]=useState(false),[selected,setSelected]=useState<Row>(),[form]=Form.useForm();const load=()=>Promise.all([api('/resources'),api('/actions')]).then(([r,a])=>{setRows(normalizeResources(r));setActions(a)}).catch(e=>message.error(e.message));useEffect(()=>{void load()},[]);const tree=useMemo(()=>{const nodes=new Map(rows.map(r=>[r.id,{key:r.id,title:`${r.name_fa} (${r.resource_key})`,children:[]as any[]} ])),roots:any[]=[];rows.forEach(r=>{const n=nodes.get(r.id)!;if(r.parent_id&&nodes.has(r.parent_id))nodes.get(r.parent_id)!.children.push(n);else roots.push(n)});return roots},[rows]);const save=async(v:Row)=>{try{await api('/resources',{method:'POST',body:JSON.stringify({...v,parentId:v.parentId||null})});setOpen(false);form.resetFields();load();message.success('منبع ایجاد شد')}catch(e){message.error((e as Error).message)}};const assigned=(selected?.actions??[])as Row[];return <Space direction="vertical" style={{width:'100%'}}><Card title="درخت منابع" extra={<Button type="primary" onClick={()=>setOpen(true)}>گره جدید</Button>}><Tree treeData={tree} defaultExpandAll onSelect={keys=>setSelected(rows.find(r=>r.id===keys[0]))}/></Card>{selected&&<Card title={`عملیات مجاز: ${selected.name_fa}`}><Space wrap>{actions.map(a=>{const on=assigned.some(x=>x.id===a.id);return <Button key={a.id} type={on?'primary':'default'} onClick={()=>api(`/resources/${selected.id}/actions/${a.id}`,{method:on?'DELETE':'PUT'}).then(load)}>{a.name_fa} ({a.action_key})</Button>})}</Space></Card>}<Modal open={open} title="گره جدید درخت دسترسی" onCancel={()=>setOpen(false)} onOk={()=>form.submit()}><Form form={form} layout="vertical" onFinish={save}><Form.Item name="resourceKey" label="کلید یکتا" rules={required}><Input placeholder="page:admin.users"/></Form.Item><Form.Item name="type" label="نوع" rules={required}><Select options={['APPLICATION','MODULE','PAGE','UI_COMPONENT','BUSINESS_RESOURCE','EXTERNAL_RESOURCE'].map(value=>({value,label:value}))}/></Form.Item><Form.Item name="parentId" label="والد"><Select allowClear options={rows.map(r=>({value:r.id,label:r.name_fa}))}/></Form.Item><Form.Item name="nameFa" label="نام فارسی" rules={required}><Input/></Form.Item><Form.Item name="nameEn" label="نام انگلیسی" rules={required}><Input/></Form.Item><Form.Item name="ownerDomain" label="دامنه مالک"><Input/></Form.Item></Form></Modal></Space>}
function Grants(){const[users,setUsers]=useState<Row[]>([]),[resources,setResources]=useState<Row[]>([]),[user,setUser]=useState<string>(),[grants,setGrants]=useState<Row[]>([]),[form]=Form.useForm();useEffect(()=>{Promise.all([api('/users'),api('/resources')]).then(([u,r])=>{setUsers(u);setResources(normalizeResources(r))}).catch(e=>message.error(e.message))},[]);const loadGrants=(id:string)=>{setUser(id);api(`/users/${id}/grants`).then(setGrants)};const grant=async(v:Row)=>{await api('/grants',{method:'POST',body:JSON.stringify({userId:user,resourceId:v.resourceId,actionId:v.actionId,relation:'allowed',expiresAt:null})});form.resetFields();loadGrants(user!);message.success('دسترسی اعطا شد')};return <Space direction="vertical" style={{width:'100%'}}><Card title="انتخاب کاربر"><Select style={{width:360}} placeholder="کاربر" onChange={loadGrants} options={users.map(u=>({value:u.id,label:`${u.display_name??u.username} — ${u.username}`}))}/></Card>{user&&<><Card title="اعطای دسترسی"><Form form={form} layout="inline" onFinish={grant}><Form.Item name="resourceId" rules={required}><Select showSearch optionFilterProp="label" style={{width:320}} placeholder="منبع" options={resources.map(r=>({value:r.id,label:`${r.name_fa} (${r.resource_key})`}))}/></Form.Item><Form.Item noStyle shouldUpdate>{()=>{const r=resources.find(x=>x.id===form.getFieldValue('resourceId'));return <Form.Item name="actionId" rules={required}><Select style={{width:220}} placeholder="عملیات" options={(r?.actions??[]).map((a:Row)=>({value:a.id,label:`${a.nameFa} (${a.key})`}))}/></Form.Item>}}</Form.Item><Button type="primary" htmlType="submit">اعطا</Button></Form></Card><Card title="دسترسی‌های فعال"><Table rowKey="id" dataSource={grants} pagination={false} columns={[{title:'منبع',dataIndex:'name_fa'},{title:'کلید',dataIndex:'resource_key'},{title:'عملیات',dataIndex:'action_name_fa'},{title:'',render:(_,g)=><Popconfirm title="دسترسی لغو شود؟" onConfirm={()=>api(`/grants/${g.id}`,{method:'DELETE'}).then(()=>loadGrants(user))}><Button danger>لغو</Button></Popconfirm>}]}/></Card></>}</Space>}
function IdentityAndRoles(){
  const[users,setUsers]=useState<Row[]>([]),[groups,setGroups]=useState<Row[]>([]),[roles,setRoles]=useState<Row[]>([]),[assignments,setAssignments]=useState<Row[]>([]),[roleOpen,setRoleOpen]=useState(false),[roleForm]=Form.useForm(),[assignmentForm]=Form.useForm();
  const load=()=>Promise.all([api('/users'),api('/groups'),api('/roles'),api('/role-assignments')]).then(([u,g,r,a])=>{setUsers(u);setGroups(g);setRoles(r);setAssignments(a)}).catch(e=>message.error(e.message));
  useEffect(()=>{void load()},[]);
  const createRole=async(v:Row)=>{try{await api('/roles',{method:'POST',body:JSON.stringify(v)});setRoleOpen(false);roleForm.resetFields();await load();message.success('نقش کاربردی ایجاد شد')}catch(e){message.error((e as Error).message)}};
  const assign=async(v:Row)=>{try{await api('/role-assignments',{method:'POST',body:JSON.stringify({...v,expiresAt:v.expiresAt||null})});assignmentForm.resetFields();await load();message.success('نقش تخصیص یافت')}catch(e){message.error((e as Error).message)}};
  const subjectOptions=(type:string)=>(type==='GROUP'?groups:users).map(item=>({value:item.id,label:type==='GROUP'?`${item.display_name} — ${item.normalized_path}`:`${item.display_name??item.username} — ${item.username}`}));
  return <Space direction="vertical" size={16} style={{width:'100%'}}>
    <Alert showIcon type="info" message="گروه‌های سازمانی نقش نیستند" description="گروه‌ها از Keycloak/LDAP همگام و فقط‌خواندنی‌اند. نقش‌های کاربردی بسته‌های قابلیت هستند و می‌توان آن‌ها را به کاربر یا گروه تخصیص داد."/>
    <Card title="گروه‌های سازمانی همگام‌شده"><Table rowKey="id" dataSource={groups} pagination={{pageSize:8}} columns={[{title:'نام',dataIndex:'display_name'},{title:'مسیر پایدار',dataIndex:'normalized_path'},{title:'شناسه خارجی',dataIndex:'external_id'},{title:'وضعیت',render:(_,r)=><Tag color={r.status==='ACTIVE'?'green':'default'}>{r.status}</Tag>},{title:'آخرین همگام‌سازی',dataIndex:'sync_at',render:v=>v?new Date(v).toLocaleString('fa-IR'):'—'}]}/></Card>
    <Card title="نقش‌های کاربردی" extra={<Button type="primary" onClick={()=>setRoleOpen(true)}>نقش جدید</Button>}><Table rowKey="id" dataSource={roles} pagination={false} columns={[{title:'کلید نقش',dataIndex:'role_key'},{title:'نام فارسی',dataIndex:'name_fa'},{title:'نام انگلیسی',dataIndex:'name_en'},{title:'وضعیت',dataIndex:'status'}]}/></Card>
    <Card title="تخصیص نقش"><Form form={assignmentForm} layout="inline" onFinish={assign} initialValues={{subjectType:'USER'}}><Form.Item name="subjectType" rules={required}><Select style={{width:140}} options={[{value:'USER',label:'کاربر'},{value:'GROUP',label:'گروه'}]}/></Form.Item><Form.Item noStyle shouldUpdate={(a,b)=>a.subjectType!==b.subjectType}>{()=>{const type=assignmentForm.getFieldValue('subjectType');return <Form.Item name="subjectId" rules={required}><Select showSearch optionFilterProp="label" style={{width:340}} placeholder={type==='GROUP'?'انتخاب گروه':'انتخاب کاربر'} options={subjectOptions(type)}/></Form.Item>}}</Form.Item><Form.Item name="roleId" rules={required}><Select style={{width:260}} placeholder="نقش" options={roles.map(r=>({value:r.id,label:`${r.name_fa} (${r.role_key})`}))}/></Form.Item><Button type="primary" htmlType="submit">تخصیص</Button></Form><Table style={{marginTop:16}} rowKey={r=>`${r.subject_type}:${r.subject_id}:${r.role_id}`} dataSource={assignments} pagination={{pageSize:8}} columns={[{title:'نوع',dataIndex:'subject_type',render:v=>v==='GROUP'?'گروه':'کاربر'},{title:'کاربر/گروه',dataIndex:'subject_name'},{title:'نقش',dataIndex:'role_key'},{title:'انقضا',dataIndex:'expires_at',render:v=>v?new Date(v).toLocaleString('fa-IR'):'بدون انقضا'},{title:'',render:(_,r)=><Popconfirm title="این تخصیص لغو شود؟" onConfirm={()=>api(`/role-assignments/${r.subject_type}/${r.subject_id}/${r.role_id}`,{method:'DELETE'}).then(load).catch(e=>message.error((e as Error).message))}><Button danger>لغو</Button></Popconfirm>}]}/></Card>
    <Modal open={roleOpen} title="تعریف نقش کاربردی" onCancel={()=>setRoleOpen(false)} onOk={()=>roleForm.submit()}><Form form={roleForm} layout="vertical" onFinish={createRole}><Form.Item name="roleKey" label="کلید پایدار نقش" rules={required}><Input placeholder="hr-supervisor"/></Form.Item><Form.Item name="nameFa" label="نام فارسی" rules={required}><Input/></Form.Item><Form.Item name="nameEn" label="نام انگلیسی" rules={required}><Input/></Form.Item></Form></Modal>
  </Space>;
}
function App(){return <Card><Typography.Title level={3}>مرکز مدیریت Aurevia</Typography.Title><Alert showIcon type="info" message="تعریف میکروفرانت، مدل‌سازی درخت منابع و تخصیص دسترسی مستقیم به کاربران"/><Tabs style={{marginTop:16}} items={[{key:'access-studio',label:'استودیوی دسترسی',children:<AccessStudio/>},{key:'panels',label:'میکروفرانت‌ها',children:<PanelsView/>},{key:'proxy-routes',label:'راهبری Proxy',children:<ProxyRouteManagement api={api}/>},{key:'outbound-auth',label:'پروفایل‌های احراز هویت سرویس‌ها',children:<OutboundAuthProfiles api={api}/>},{key:'superset',label:'گزارش‌ها و داشبوردها',children:<SupersetAssets/>},{key:'identity',label:'گروه‌ها و نقش‌ها',children:<IdentityAndRoles/>},{key:'logs',label:'لاگ‌ها',children:<LogsView/>}]}/></Card>}
export const mount:RemoteModule['mount']=(el:HTMLElement,_ctx:RemoteContext)=>{const root=createRoot(el);root.render(<App/>);return()=>root.unmount()};
