import React,{useEffect,useState}from'react';
import{Alert,Button,Card,Checkbox,Form,Input,InputNumber,Modal,Popconfirm,Select,Space,Table,Tabs,Tag,Typography,message}from'antd';

type Row=Record<string,any>;
export type AdminApi=(path:string,init?:RequestInit)=>Promise<any>;
const required=[{required:true,message:'این فیلد الزامی است'}];
const methods=['GET','HEAD','OPTIONS','POST','PUT','PATCH','DELETE'];

export function ProxyRouteManagement({api}:{api:AdminApi}){
 const[targets,setTargets]=useState<Row[]>([]),[authProfiles,setAuthProfiles]=useState<Row[]>([]),[routes,setRoutes]=useState<Row[]>([]),[panels,setPanels]=useState<Row[]>([]),[resources,setResources]=useState<Row[]>([]),[selectedRoute,setSelectedRoute]=useState<Row>(),[operations,setOperations]=useState<Row[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState<string>();
 const[targetOpen,setTargetOpen]=useState(false),[routeOpen,setRouteOpen]=useState(false),[operationOpen,setOperationOpen]=useState(false),[editingTarget,setEditingTarget]=useState<Row>(),[editingRoute,setEditingRoute]=useState<Row>(),[editingOperation,setEditingOperation]=useState<Row>();
 const[targetForm]=Form.useForm(),[routeForm]=Form.useForm(),[operationForm]=Form.useForm();
 const load=async()=>{setLoading(true);setError(undefined);try{const[t,a,r,p,res]=await Promise.all([api('/service-targets'),api('/outbound-auth-profiles'),api('/proxy-routes'),api('/panels'),api('/resources')]);setTargets(t);setAuthProfiles(a);setRoutes(r);setPanels(p);setResources(res.map((x:Row)=>({...x,actions:JSON.parse(x.actions_json??'[]')})))}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 const loadOperations=async(route:Row)=>{setSelectedRoute(route);setOperations(await api(`/proxy-routes/${route.id}/operations`))};
 useEffect(()=>{void load()},[]);
 const openTarget=(row?:Row)=>{setEditingTarget(row);targetForm.setFieldsValue(row?{...row,gatewayBaseUrl:row.gateway_base_url,upstreamBasePath:row.upstream_base_path,tlsProfileRef:row.tls_profile_ref,secretRef:row.secret_ref,healthCheckPath:row.health_check_path,connectTimeoutMs:row.connect_timeout_ms,responseTimeoutMs:row.response_timeout_ms,maxResponseSize:row.max_response_size,outboundAuthProfileId:row.outbound_auth_profile_id}:{active:true,environment:'OPERATION',upstreamBasePath:'/',healthCheckPath:'/health',connectTimeoutMs:3000,responseTimeoutMs:10000,maxResponseSize:10485760,outboundAuthProfileId:authProfiles.find(p=>p.code==='public-iam-forward')?.id});setTargetOpen(true)};
 const saveTarget=async(v:Row)=>{await api(editingTarget?`/service-targets/${editingTarget.id}?version=${editingTarget.version}`:'/service-targets',{method:editingTarget?'PUT':'POST',body:JSON.stringify(v)});message.success('Service Target ذخیره شد');setTargetOpen(false);await load()};
 const openRoute=(row?:Row,panelId?:string)=>{setEditingRoute(row);routeForm.setFieldsValue(row?{...row,panelId:row.panel_id,serviceTargetId:row.service_target_id,pathPrefix:row.path_prefix,stripPrefix:row.strip_prefix,rewritePattern:row.rewrite_pattern,rewriteReplacement:row.rewrite_replacement,allowedMethods:row.allowed_methods,preserveHost:row.preserve_host,retryEnabled:row.retry_enabled,maxRetries:row.max_retries}:{active:true,panelId,stripPrefix:1,priority:0,allowedMethods:['GET'],preserveHost:false,retryEnabled:false,maxRetries:0});setRouteOpen(true)};
 const saveRoute=async(v:Row)=>{await api('/proxy-routes/validate',{method:'POST',body:JSON.stringify(v)});await api(editingRoute?`/proxy-routes/${editingRoute.id}?version=${editingRoute.version}`:'/proxy-routes',{method:editingRoute?'PUT':'POST',body:JSON.stringify(v)});message.success('مسیر پراکسی ذخیره شد');setRouteOpen(false);await load()};
 const openOperation=(row?:Row)=>{setEditingOperation(row);operationForm.setFieldsValue(row?{httpMethod:row.http_method,pathPattern:row.path_pattern,resourceKey:row.resource_key,actionKey:row.action_key,authorizationRequired:row.authorization_required,dataPolicyKey:row.data_policy_key,active:row.active,maxBodyBytes:row.max_body_bytes}:{httpMethod:'GET',pathPattern:'/api/v1/',authorizationRequired:true,active:true,maxBodyBytes:1048576});setOperationOpen(true)};
 const saveOperation=async(v:Row)=>{if(!selectedRoute)return;await api(editingOperation?`/proxy-routes/${selectedRoute.id}/operations/${editingOperation.id}?version=${editingOperation.version}`:`/proxy-routes/${selectedRoute.id}/operations`,{method:editingOperation?'PUT':'POST',body:JSON.stringify(v)});message.success('عملیات مسیر ذخیره شد');setOperationOpen(false);await loadOperations(selectedRoute)};
 const preview=async(row:Row)=>{const path=window.prompt('یک مسیر ورودی وارد کنید',`${row.normalized_path_prefix}api/v1/employees`);if(!path)return;try{const result=await api('/proxy-routes/preview',{method:'POST',body:JSON.stringify({routeId:row.id,path})});Modal.info({title:'پیش‌نمایش تبدیل مسیر',content:<><Typography.Text code>{result.incomingPath}</Typography.Text><br/>↓<br/><Typography.Text code>{result.upstreamPath}</Typography.Text></>})}catch(e){message.error((e as Error).message)}};
 const resolveTest=async()=>{const path=window.prompt('مسیر کامل درخواست','/hr-micro/api/v1/employees');if(!path)return;const method=window.prompt('HTTP Method','GET')||'GET';try{const result=await api('/proxy-routes/resolve-test',{method:'POST',body:JSON.stringify({path,method})});Modal.info({title:'نتیجه Route Resolution',content:<pre style={{direction:'ltr',whiteSpace:'pre-wrap'}}>{JSON.stringify(result,null,2)}</pre>})}catch(e){message.error((e as Error).message)}};
 const targetTab=<Card title="Service Targets" extra={<Space><Button onClick={()=>void load()}>بازخوانی</Button><Button type="primary" onClick={()=>openTarget()}>Target جدید</Button></Space>}><Alert showIcon type="info" message="مقصدها فقط Gatewayهای allowlisted هستند" description="Secret و کلید خصوصی ذخیره نمی‌شود؛ فقط reference امن TLS/Secret Store ثبت می‌گردد." style={{marginBottom:16}}/><Table rowKey="id" loading={loading} dataSource={targets} pagination={{pageSize:10}} columns={[{title:'کد',dataIndex:'code'},{title:'نام',dataIndex:'name'},{title:'Gateway',dataIndex:'gateway_base_url'},{title:'محیط',dataIndex:'environment'},{title:'مسیرها',dataIndex:'route_count'},{title:'وضعیت',render:(_,r)=><Tag color={r.active?'green':'default'}>{r.active?'فعال':'غیرفعال'}</Tag>},{title:'عملیات',render:(_,r)=><Space><Button onClick={()=>openTarget(r)}>ویرایش</Button><Button onClick={()=>api(`/service-targets/${r.id}/health-check`,{method:'POST'}).then(x=>message[x.healthy?'success':'warning'](`Gateway: HTTP ${x.status} — ${x.latencyMs}ms`)).catch(e=>message.error(e.message))}>تست اتصال</Button><Popconfirm title="وضعیت تغییر کند؟" onConfirm={()=>api(`/service-targets/${r.id}/status?version=${r.version}`,{method:'PATCH',body:JSON.stringify({active:!r.active})}).then(load)}><Button>{r.active?'غیرفعال':'فعال'}</Button></Popconfirm></Space>}]}/></Card>;
 const routeTab=<Card title="Proxy Routes" extra={<Space><Button onClick={()=>void resolveTest()}>تست Resolution</Button><Button type="primary" onClick={()=>openRoute()}>مسیر جدید</Button></Space>}><Table rowKey="id" loading={loading} dataSource={routes} pagination={{pageSize:10}} columns={[{title:'کد',dataIndex:'code'},{title:'پنل',dataIndex:'panel_name'},{title:'Prefix',dataIndex:'normalized_path_prefix'},{title:'Target',dataIndex:'target_code'},{title:'اولویت',dataIndex:'priority'},{title:'Methodها',render:(_,r)=><Space wrap>{(r.allowed_methods??[]).map((m:string)=><Tag key={m}>{m}</Tag>)}</Space>},{title:'وضعیت',render:(_,r)=><Tag color={r.active?'green':'default'}>{r.active?'فعال':'غیرفعال'}</Tag>},{title:'عملیات',render:(_,r)=><Space><Button onClick={()=>openRoute(r)}>ویرایش</Button><Button onClick={()=>void preview(r)}>Preview</Button><Button type="primary" ghost onClick={()=>void loadOperations(r)}>Operationها</Button></Space>}]}/></Card>;
 const operationTab=<Card title={selectedRoute?`Route Operations — ${selectedRoute.code}`:'Route Operations'} extra={<Space><Select style={{width:280}} placeholder="انتخاب Route" value={selectedRoute?.id} options={routes.map(r=>({value:r.id,label:`${r.code} — ${r.normalized_path_prefix}`}))} onChange={id=>void loadOperations(routes.find(r=>r.id===id)!)} /><Button type="primary" disabled={!selectedRoute} onClick={()=>openOperation()}>Operation جدید</Button></Space>}>{!selectedRoute?<Alert type="info" showIcon message="ابتدا یک Route انتخاب کنید"/>:<Table rowKey="id" dataSource={operations} pagination={false} columns={[{title:'Method',dataIndex:'http_method'},{title:'Pattern',dataIndex:'normalized_path_pattern'},{title:'Resource : Action',render:(_,r)=><Typography.Text code>{r.resource_key}:{r.action_key}</Typography.Text>},{title:'مجوز',render:(_,r)=>r.authorization_required?<Tag color="blue">OpenFGA</Tag>:<Tag>Public</Tag>},{title:'وضعیت',render:(_,r)=><Tag color={r.active?'green':'default'}>{r.active?'فعال':'غیرفعال'}</Tag>},{title:'عملیات',render:(_,r)=><Space><Button onClick={()=>openOperation(r)}>ویرایش</Button><Popconfirm title="Operation غیرفعال شود؟" onConfirm={()=>api(`/proxy-routes/${selectedRoute.id}/operations/${r.id}?version=${r.version}`,{method:'DELETE'}).then(()=>loadOperations(selectedRoute))}><Button danger>غیرفعال</Button></Popconfirm></Space>}]}/>}</Card>;
 return <Space direction="vertical" size={16} style={{width:'100%'}}>{error&&<Alert showIcon type="error" message="خطا در دریافت تنظیمات Proxy" description={error}/>}<Tabs items={[{key:'targets',label:'Service Targets',children:targetTab},{key:'routes',label:'Proxy Routes',children:routeTab},{key:'operations',label:'Route Operations',children:operationTab}]}/>
 <Modal open={targetOpen} title={editingTarget?'ویرایش Service Target':'Service Target جدید'} onCancel={()=>setTargetOpen(false)} onOk={()=>targetForm.submit()} width={800}><Form form={targetForm} layout="vertical" onFinish={v=>saveTarget(v).catch(e=>message.error(e.message))}><Space wrap align="start"><Form.Item name="code" label="کد" rules={required}><Input/></Form.Item><Form.Item name="name" label="نام" rules={required}><Input/></Form.Item><Form.Item name="environment" label="محیط" rules={required}><Select style={{width:180}} options={['OPERATION','STAGING'].map(value=>({value,label:value}))}/></Form.Item><Form.Item name="outboundAuthProfileId" label="Outbound Auth Profile" rules={required}><Select style={{width:300}} options={authProfiles.filter(p=>p.active).map(p=>({value:p.id,label:`${p.name} (${p.auth_mode})`}))}/></Form.Item><Form.Item name="gatewayBaseUrl" label="آدرس کامل Gateway" rules={[...required,{type:'url'}]}><Input style={{width:360}} placeholder="http://operation-gateway:80"/></Form.Item><Form.Item name="upstreamBasePath" label="Upstream Base Path" rules={required}><Input/></Form.Item><Form.Item name="healthCheckPath" label="Health Path" rules={required}><Input/></Form.Item><Form.Item name="tlsProfileRef" label="TLS Profile Ref"><Input placeholder="tls://gateway-client"/></Form.Item><Form.Item name="secretRef" label="Secret Ref"><Input placeholder="secret://gateway-client"/></Form.Item><Form.Item name="connectTimeoutMs" label="Connect Timeout"><InputNumber min={100}/></Form.Item><Form.Item name="responseTimeoutMs" label="Response Timeout"><InputNumber min={100}/></Form.Item><Form.Item name="maxResponseSize" label="Max Response Bytes"><InputNumber min={1024}/></Form.Item><Form.Item name="active" valuePropName="checked"><Checkbox>فعال</Checkbox></Form.Item></Space><Form.Item name="description" label="توضیح"><Input.TextArea/></Form.Item></Form></Modal>
 <Modal open={routeOpen} title={editingRoute?'ویرایش Proxy Route':'Proxy Route جدید'} onCancel={()=>setRouteOpen(false)} onOk={()=>routeForm.submit()} width={850}><Form form={routeForm} layout="vertical" onFinish={v=>saveRoute(v).catch(e=>message.error(e.message))}><Space wrap align="start"><Form.Item name="code" label="کد" rules={required}><Input/></Form.Item><Form.Item name="panelId" label="Panel" rules={required}><Select style={{width:250}} options={panels.map(p=>({value:p.id,label:`${p.name_fa} (${p.slug})`}))}/></Form.Item><Form.Item name="serviceTargetId" label="Service Target" rules={required}><Select style={{width:250}} options={targets.map(t=>({value:t.id,label:t.code}))}/></Form.Item><Form.Item name="pathPrefix" label="Path Prefix" rules={required}><Input placeholder="/hr-micro/"/></Form.Item><Form.Item name="stripPrefix" label="Strip Segments"><InputNumber min={0} max={20}/></Form.Item><Form.Item name="priority" label="Priority"><InputNumber/></Form.Item><Form.Item name="allowedMethods" label="Allowed Methods" rules={required}><Select mode="multiple" style={{width:360}} options={methods.map(value=>({value,label:value}))}/></Form.Item><Form.Item name="rewritePattern" label="Rewrite Prefix"><Input placeholder="^/api/v1"/></Form.Item><Form.Item name="rewriteReplacement" label="Rewrite Replacement"><Input placeholder="/hr-service/api/v1"/></Form.Item><Form.Item name="retryEnabled" valuePropName="checked"><Checkbox>Retry فقط برای روش‌های امن</Checkbox></Form.Item><Form.Item name="maxRetries" label="Max Retries"><InputNumber min={0} max={3}/></Form.Item><Form.Item name="preserveHost" valuePropName="checked"><Checkbox>Preserve Host</Checkbox></Form.Item><Form.Item name="active" valuePropName="checked"><Checkbox>فعال</Checkbox></Form.Item></Space></Form></Modal>
 <Modal open={operationOpen} title={editingOperation?'ویرایش Route Operation':'Route Operation جدید'} onCancel={()=>setOperationOpen(false)} onOk={()=>operationForm.submit()} width={760}><Form form={operationForm} layout="vertical" onFinish={v=>saveOperation(v).catch(e=>message.error(e.message))}><Space wrap align="start"><Form.Item name="httpMethod" label="HTTP Method" rules={required}><Select style={{width:150}} options={methods.map(value=>({value,label:value}))}/></Form.Item><Form.Item name="pathPattern" label="Path Pattern" rules={required}><Input style={{width:300}} placeholder="/api/v1/employees/{id}"/></Form.Item><Form.Item name="resourceKey" label="Resource" rules={required}><Select showSearch optionFilterProp="label" style={{width:320}} options={resources.map(r=>({value:r.resource_key,label:`${r.name_fa} (${r.resource_key})`}))} onChange={()=>operationForm.setFieldValue('actionKey',undefined)}/></Form.Item><Form.Item noStyle shouldUpdate>{()=>{const selected=resources.find(r=>r.resource_key===operationForm.getFieldValue('resourceKey'));return <Form.Item name="actionKey" label="Action" rules={required}><Select style={{width:220}} options={(selected?.actions??[]).map((a:Row)=>({value:a.key??a.action_key,label:`${a.nameFa??a.name_fa} (${a.key??a.action_key})`}))}/></Form.Item>}}</Form.Item><Form.Item name="dataPolicyKey" label="Data Policy"><Input/></Form.Item><Form.Item name="maxBodyBytes" label="Max Body Bytes"><InputNumber min={0}/></Form.Item><Form.Item name="authorizationRequired" valuePropName="checked"><Checkbox>نیازمند OpenFGA</Checkbox></Form.Item><Form.Item name="active" valuePropName="checked"><Checkbox>فعال</Checkbox></Form.Item></Space></Form></Modal></Space>;
}
