package com.aurevia.bff.outboundauth;
import com.aurevia.bff.api.AuthorizationServiceClient;import org.springframework.stereotype.Component;import reactor.core.publisher.Mono;
@Component public class LegacyTokenManager {
 private final AuthorizationServiceClient auth;private final LegacyTokenCache cache;private final SecretResolver secrets;private final LegacyTokenClient client;private final LegacyTokenResponseParser parser;private final LegacyTokenRefreshCoordinator coordinator;private final LegacyTokenAuditPublisher audit;
 LegacyTokenManager(AuthorizationServiceClient a,LegacyTokenCache c,SecretResolver s,LegacyTokenClient l,LegacyTokenResponseParser p,LegacyTokenRefreshCoordinator r,LegacyTokenAuditPublisher u){auth=a;cache=c;secrets=s;client=l;parser=p;coordinator=r;audit=u;}
 Mono<OutboundCredential> resolve(OutboundTokenProvider.ServiceTarget target){return profile(target).flatMap(p->cache.read(p.id(),p.version(),p.skewSeconds()).doOnNext(x->audit.event("cache-hit",p.id(),"success")).switchIfEmpty(Mono.defer(()->{audit.event("cache-miss",p.id(),"success");return coordinator.once(cache.lock(p.id()),()->cache.read(p.id(),p.version(),p.skewSeconds()).switchIfEmpty(acquire(p)),()->cache.read(p.id(),p.version(),p.skewSeconds()));})).map(t->new OutboundCredential(t.tokenType(),t.accessToken(),true)));}
 public Mono<Void> invalidate(String profileId){return cache.invalidate(profileId).doOnSuccess(v->audit.event("invalidate",profileId,"success"));}
 Mono<Void> invalidate(OutboundTokenProvider.ServiceTarget target){return invalidate(target.authProfileId());}
 public Mono<Boolean> cacheStatus(String id){return cache.cached(id);}public Mono<OutboundCredential> test(String id){OutboundTokenProvider.ServiceTarget t=new OutboundTokenProvider.ServiceTarget("test",id,OutboundAuthMode.LEGACY_SERVICE_TOKEN,-1);return profile(t).flatMap(this::acquire).map(x->new OutboundCredential(x.tokenType(),x.accessToken(),true));}
 private Mono<OutboundAuthProfile> profile(OutboundTokenProvider.ServiceTarget t){return auth.outboundAuthProfile(t.authProfileId()).map(OutboundAuthProfile::from).flatMap(p->p.mode()!=OutboundAuthMode.LEGACY_SERVICE_TOKEN?Mono.error(new IllegalStateException("Not a Legacy profile")):Mono.just(p));}
 private Mono<LegacyTokenCache.Cached> acquire(OutboundAuthProfile p){return secrets.resolve(new SecretResolver.SecretReference(p.credentialSecretRef())).flatMap(secret->client.acquire(p,secret).map(bytes->parser.parse(bytes,p)).flatMap(token->cache.write(p.id(),token,secret.version(),p.version()).thenReturn(new LegacyTokenCache.Cached(token.accessToken(),token.refreshToken(),token.tokenType(),token.expiresAt(),secret.version(),p.version())))).doOnSuccess(x->audit.event("acquire",p.id(),"success")).doOnError(e->audit.event("acquire",p.id(),"failure"));}
}
