package com.aurevia.bff.outboundauth;
import java.time.Duration;import java.util.Map;import java.util.concurrent.atomic.AtomicInteger;import java.util.concurrent.atomic.AtomicLong;
import io.netty.channel.ChannelOption;import reactor.netty.http.client.HttpClient;import reactor.netty.resources.ConnectionProvider;
import org.springframework.beans.factory.annotation.Value;import org.springframework.http.MediaType;import org.springframework.http.HttpStatusCode;import org.springframework.stereotype.Component;import org.springframework.util.LinkedMultiValueMap;import org.springframework.http.client.reactive.ReactorClientHttpConnector;import org.springframework.web.reactive.function.BodyInserters;import org.springframework.web.reactive.function.client.WebClient;import org.springframework.web.reactive.function.client.WebClientRequestException;import reactor.core.publisher.Mono;import reactor.util.retry.Retry;
@Component class LegacyTokenClient {
 private final WebClient client;private final String approvedRef;private final AtomicInteger failures=new AtomicInteger();private final AtomicLong circuitUntil=new AtomicLong();private final AtomicLong rateWindow=new AtomicLong();private final AtomicInteger rateCount=new AtomicInteger();
 LegacyTokenClient(WebClient.Builder ignored,@Value("${aurevia.legacy.token-connection.ref:connection://disabled}") String ref,@Value("${aurevia.legacy.token-connection.base-url:https://invalid.invalid}") String base,@Value("${aurevia.legacy.allow-insecure-local:false}") boolean insecure){if(!base.startsWith("https://")&&!(insecure&&base.startsWith("http://")))throw new IllegalStateException("Legacy token connection requires TLS");approvedRef=ref;ConnectionProvider pool=ConnectionProvider.builder("legacy-token-endpoints").maxConnections(20).pendingAcquireTimeout(Duration.ofSeconds(2)).build();HttpClient http=HttpClient.create(pool).followRedirect(false).option(ChannelOption.CONNECT_TIMEOUT_MILLIS,3000).responseTimeout(Duration.ofSeconds(15));client=WebClient.builder().clientConnector(new ReactorClientHttpConnector(http)).baseUrl(base).codecs(c->c.defaultCodecs().maxInMemorySize(5*1024*1024)).build();}
 Mono<byte[]> acquire(OutboundAuthProfile p,SecretResolver.ResolvedSecret secret){if(!approvedRef.equals(p.connectionRef()))return Mono.error(new IllegalStateException("Unapproved token connection"));if(System.currentTimeMillis()<circuitUntil.get())return Mono.error(new IllegalStateException("Legacy token endpoint unavailable"));if(!rateAllowed())return Mono.error(new IllegalStateException("Legacy token acquisition rate limited"));var request=client.post().uri(p.endpointPath()).accept(MediaType.APPLICATION_JSON);Mono<byte[]> result;
  if("JSON".equals(p.requestFormat()))result=request.contentType(MediaType.APPLICATION_JSON).bodyValue(Map.of("username",required(secret.username()),"password",required(secret.password()))).retrieve().bodyToMono(byte[].class);
  else {LinkedMultiValueMap<String,String> form=new LinkedMultiValueMap<>();if(secret.username()!=null)form.add("username",secret.username());if(secret.password()!=null)form.add("password",secret.password());if(secret.clientId()!=null)form.add("client_id",secret.clientId());if(secret.clientSecret()!=null)form.add("client_secret",secret.clientSecret());if(p.scope()!=null)form.add("scope",p.scope());if(p.audience()!=null)form.add("audience",p.audience());if("OAUTH_CLIENT_CREDENTIALS".equals(p.requestFormat()))form.add("grant_type","client_credentials");var spec=request.contentType(MediaType.APPLICATION_FORM_URLENCODED);if("HTTP_BASIC".equals(p.requestFormat()))spec.headers(h->h.setBasicAuth(required(secret.username()),required(secret.password())));result=spec.body(BodyInserters.fromFormData(form)).retrieve().bodyToMono(byte[].class);}
  return result.timeout(Duration.ofMillis(p.responseTimeoutMs())).retryWhen(Retry.max(1).filter(WebClientRequestException.class::isInstance)).flatMap(bytes->bytes.length>p.maxSize()?Mono.error(new IllegalStateException("Token response too large")):Mono.just(bytes)).doOnSuccess(x->failures.set(0)).doOnError(x->{if(!(x instanceof org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest)&&failures.incrementAndGet()>=5)circuitUntil.set(System.currentTimeMillis()+30000);});}
 private boolean rateAllowed(){long second=System.currentTimeMillis()/1000;long previous=rateWindow.get();if(previous!=second&&rateWindow.compareAndSet(previous,second))rateCount.set(0);return rateCount.incrementAndGet()<=10;}
 private static String required(String v){if(v==null||v.isBlank())throw new IllegalStateException("Legacy credential incomplete");return v;}
}
