import os
SECRET_KEY = os.environ["SUPERSET_SECRET_KEY"]
SESSION_COOKIE_NAME = "AUREVIA_PUBLIC_SUPERSET"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "Lax"
PUBLIC_ROLE_LIKE = None
FEATURE_FLAGS = {"ENABLE_VIEWERS": True}
TALISMAN_CONFIG = {"content_security_policy": {"frame-ancestors": ["'self'"]}}
