import os

SECRET_KEY = os.environ["SUPERSET_SECRET_KEY"]
SQLALCHEMY_DATABASE_URI = os.environ["SUPERSET_DATABASE_URI"]
SESSION_COOKIE_NAME = "AUREVIA_PUBLIC_SUPERSET"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = os.getenv("SUPERSET_COOKIE_SECURE", "false").lower() == "true"
SESSION_COOKIE_SAMESITE = "Lax"
PUBLIC_ROLE_LIKE = None
FEATURE_FLAGS = {"ENABLE_VIEWERS": True}
ENABLE_PROXY_FIX = True
APPLICATION_ROOT = "/reports-runtime"
SESSION_COOKIE_PATH = "/reports-runtime"
TALISMAN_ENABLED = False
TALISMAN_CONFIG = {"content_security_policy": {"frame-ancestors": ["'self'"]}}
