package com.aurevia.authz.api;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.Instant;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/internal/v1/registry")
public class AccessAdminController {
 private final JdbcClient db; public AccessAdminController(JdbcClient db){this.db=db;}
 @GetMapping("/resources") public List<Map<String,Object>> resources(){return db.sql("select r.id,r.resource_key,r.type,r.parent_id,r.name_fa,r.name_en,r.owner_domain,r.status,r.version,coalesce((jsonb_agg(jsonb_build_object('id',a.id,'key',a.action_key,'nameFa',a.name_fa,'nameEn',a.name_en)) filter(where a.id is not null))::text,'[]') actions_json from resource r left join resource_action ra on ra.resource_id=r.id left join action a on a.id=ra.action_id group by r.id order by r.resource_key").query().listOfRows();}
 @PostMapping("/resources") @ResponseStatus(HttpStatus.CREATED) @Transactional public Map<String,Object> createResource(@Valid @RequestBody ResourceWrite r){UUID id=UUID.randomUUID();db.sql("insert into resource(id,resource_key,type,parent_id,name_fa,name_en,owner_domain,status) values(:id,:key,cast(:type as resource_type),:parent,:fa,:en,:owner,'ACTIVE')").param("id",id).param("key",r.resourceKey()).param("type",r.type()).param("parent",r.parentId()).param("fa",r.nameFa()).param("en",r.nameEn()).param("owner",r.ownerDomain()).update();audit("RESOURCE_CREATED","resource",r.resourceKey());return Map.of("id",id,"version",0);}
 @PutMapping("/resources/{id}") @Transactional public Map<String,Object> updateResource(@PathVariable("id") UUID id,@RequestParam("version") long version,@Valid @RequestBody ResourceWrite r){int n=db.sql("update resource set resource_key=:key,type=cast(:type as resource_type),parent_id=:parent,name_fa=:fa,name_en=:en,owner_domain=:owner,version=version+1,updated_at=now() where id=:id and version=:version").param("id",id).param("version",version).param("key",r.resourceKey()).param("type",r.type()).param("parent",r.parentId()).param("fa",r.nameFa()).param("en",r.nameEn()).param("owner",r.ownerDomain()).update();if(n==0)throw new org.springframework.dao.OptimisticLockingFailureException("resource changed or missing");audit("RESOURCE_UPDATED","resource",r.resourceKey());return Map.of("id",id,"version",version+1);}
 @GetMapping("/actions") public List<Map<String,Object>> actions(){return db.sql("select id,action_key,name_fa,name_en from action order by action_key").query().listOfRows();}
 @PostMapping("/actions") @ResponseStatus(HttpStatus.CREATED) @Transactional public Map<String,Object> createAction(@Valid @RequestBody ActionWrite a){UUID id=UUID.randomUUID();db.sql("insert into action(id,action_key,name_fa,name_en) values(:id,:key,:fa,:en)").param("id",id).param("key",a.actionKey()).param("fa",a.nameFa()).param("en",a.nameEn()).update();audit("ACTION_CREATED","action",a.actionKey());return Map.of("id",id);}
 @PutMapping("/resources/{resourceId}/actions/{actionId}") @ResponseStatus(HttpStatus.NO_CONTENT) @Transactional public void attach(@PathVariable("resourceId") UUID resourceId,@PathVariable("actionId") UUID actionId){db.sql("insert into resource_action(resource_id,action_id) values(:resource,:action) on conflict do nothing").param("resource",resourceId).param("action",actionId).update();audit("RESOURCE_ACTION_ATTACHED","resource",resourceId.toString());}
 @DeleteMapping("/resources/{resourceId}/actions/{actionId}") @ResponseStatus(HttpStatus.NO_CONTENT) @Transactional public void detach(@PathVariable("resourceId") UUID resourceId,@PathVariable("actionId") UUID actionId){db.sql("delete from resource_action where resource_id=:resource and action_id=:action").param("resource",resourceId).param("action",actionId).update();audit("RESOURCE_ACTION_DETACHED","resource",resourceId.toString());}
 @GetMapping("/users") public List<Map<String,Object>> users(){return db.sql("select id,external_id,username,display_name,email,status,version from app_user order by username").query().listOfRows();}
 @PostMapping("/users") @ResponseStatus(HttpStatus.CREATED) @Transactional public Map<String,Object> createUser(@Valid @RequestBody UserWrite u){UUID id=UUID.randomUUID();db.sql("insert into app_user(id,issuer,external_id,username,display_name,email) values(:id,:issuer,:external,:username,:display,:email)").param("id",id).param("issuer",u.issuer()).param("external",u.externalId()).param("username",u.username()).param("display",u.displayName()).param("email",u.email()).update();audit("USER_REGISTERED","user",u.username());return Map.of("id",id,"version",0);}
 @GetMapping("/users/{id}/grants") public List<Map<String,Object>> grants(@PathVariable("id") UUID id){return db.sql("select g.id,g.resource_id,r.resource_key,r.name_fa,r.name_en,g.action_id,a.action_key,a.name_fa action_name_fa,g.relation,g.expires_at,g.status,g.version from authorization_grant g join resource r on r.id=g.resource_id join action a on a.id=g.action_id where g.subject_type='USER' and g.subject_id=:id and g.status='ACTIVE' order by r.resource_key,a.action_key").param("id",id).query().listOfRows();}
 @PostMapping("/grants") @ResponseStatus(HttpStatus.CREATED) @Transactional public Map<String,Object> grant(@Valid @RequestBody GrantWrite g){UUID id=UUID.randomUUID();db.sql("insert into authorization_grant(id,subject_type,subject_id,resource_id,action_id,relation,expires_at) values(:id,'USER',:subject,:resource,:action,:relation,:expires)").param("id",id).param("subject",g.userId()).param("resource",g.resourceId()).param("action",g.actionId()).param("relation",g.relation()).param("expires",g.expiresAt()).update();audit("GRANT_CREATED","grant",id.toString());return Map.of("id",id,"version",0);}
 @DeleteMapping("/grants/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @Transactional public void revoke(@PathVariable("id") UUID id){db.sql("update authorization_grant set status='ARCHIVED',version=version+1 where id=:id and status='ACTIVE'").param("id",id).update();audit("GRANT_REVOKED","grant",id.toString());}
 private void audit(String event,String type,String key){db.sql("insert into audit_event(actor_key,event_type,target_type,target_key,correlation_id) values('bff-admin',:event,:type,:key,:correlation)").param("event",event).param("type",type).param("key",key).param("correlation",UUID.randomUUID().toString()).update();}
 public record ResourceWrite(@NotBlank String resourceKey,@NotBlank String type,UUID parentId,@NotBlank String nameFa,@NotBlank String nameEn,String ownerDomain){}
 public record ActionWrite(@NotBlank String actionKey,@NotBlank String nameFa,@NotBlank String nameEn){}
 public record UserWrite(@NotBlank String issuer,@NotBlank String externalId,@NotBlank String username,String displayName,String email){}
 public record GrantWrite(@NotNull UUID userId,@NotNull UUID resourceId,@NotNull UUID actionId,@NotBlank String relation,Instant expiresAt){}
}
