name: aurevia-mfe-demo
services:
  mfe-admin:
    image: nginx:1.29.1-alpine
    volumes: [../mfe/nginx.conf:/etc/nginx/conf.d/default.conf:ro, ../../apps/mfe-admin/dist:/usr/share/nginx/html:ro]
    ports: ["3001:8080"]
  mfe-hr:
    image: nginx:1.29.1-alpine
    volumes: [../mfe/nginx.conf:/etc/nginx/conf.d/default.conf:ro, ../../apps/mfe-hr/dist:/usr/share/nginx/html:ro]
    ports: ["3002:8080"]
  mfe-finance:
    image: nginx:1.29.1-alpine
    volumes: [../mfe/nginx.conf:/etc/nginx/conf.d/default.conf:ro, ../../apps/mfe-finance/dist:/usr/share/nginx/html:ro]
    ports: ["3003:8080"]
  mfe-reports:
    image: nginx:1.29.1-alpine
    volumes: [../mfe/nginx.conf:/etc/nginx/conf.d/default.conf:ro, ../../apps/mfe-reports/dist:/usr/share/nginx/html:ro]
    ports: ["3004:8080"]
