server {
  listen 80;

  location /hr-micro/ {
    proxy_pass http://mock-hr:8080/;
  }

  location /finance-micro/ {
    proxy_pass http://mock-finance:8080/;
  }

  location /superset/ {
    proxy_pass http://operation-superset:8088/;
    proxy_set_header X-Forwarded-Prefix /reports-runtime;
    proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    proxy_set_header X-Forwarded-Host $http_x_forwarded_host;
    proxy_set_header X-Aurevia-Subject $http_x_aurevia_subject;
    proxy_set_header X-Correlation-ID $http_x_correlation_id;
  }
}
