import React,{Component,useEffect,useMemo,useRef,useState,type ReactNode}from'react';
import{createRoot}from'react-dom/client';import{Alert,Button,ConfigProvider,Layout,Menu,Space,Spin,Tag,Tooltip,Typography,message}from'antd';
import faIR from'antd/locale/fa_IR';import enUS from'antd/locale/en_US';import{BrowserRouter,Navigate,Route,Routes,useLocation,useNavigate}from'react-router-dom';
import type{CurrentUser,EffectiveManifest,EffectiveUserContext,HostRuntime,LoadedRemoteModule,RemoteModule,Locale,UiModuleDefinition}from'@aurevia/contracts';
import{authorization}from'@aurevia/authorization-sdk';
import{ApiError,createJsonHttpClient}from'@aurevia/http-client';
import{direction,t}from'@aurevia/i18n';import{SHManifestProvider}from'@aurevia/sh-core-ui';import{clearRemoteCache,loadRemote}from'./remote-loader';import'./styles.css';
import{activeCatalogMenuKey,activeCatalogModule,authorizedCatalogRoute,catalogMenuItems,catalogMenuTree,composeModulePath,localModulePath,moduleBasePath,type CatalogMenuItem}from'./manifest-routing';

const empty:EffectiveManifest={version:'none',expiresAt:new Date(Date.now()+60000).toISOString(),panels:[],permissions:{}};
class RemoteBoundary extends Component<{children:ReactNode;onRetry:()=>void},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?<Alert type="error" showIcon message="میکروفرانت دچار خطا شد" action={<Button onClick={()=>{this.setState({failed:false});this.props.onRetry()}}>تلاش مجدد</Button>}/>:this.props.children}}
const eventTarget=new EventTarget(),shared=new Map<string,unknown>();
const contextClient=createJsonHttpClient({basePath:''});
function createRuntime(module:UiModuleDefinition,navigate:ReturnType<typeof useNavigate>,locale:Locale,currentUser:CurrentUser|null):HostRuntime{
  const base=moduleBasePath(module),client=createJsonHttpClient({basePath:module.runtime.apiBasePath});return{mode:'embedded',moduleKey:module.moduleKey,routePrefix:module.routePrefix,
    http:{get:(p,o)=>client.get(p,o),post:(p,b,o)=>client.post(p,b,o),put:(p,b,o)=>client.put(p,b,o)},
    navigation:{navigate:p=>navigate(`${base}/${p}`.replace(/\/+/g,'/')),getModuleBasePath:()=>base},session:{getCurrentUser:()=>currentUser,subscribe:()=>()=>{}},notifications:{success:m=>message.success(m),error:m=>message.error(m)},
    events:{emit:(name,payload)=>eventTarget.dispatchEvent(new CustomEvent(name,{detail:payload})),subscribe:(name,listener)=>{const handler=(event:Event)=>listener((event as CustomEvent).detail);eventTarget.addEventListener(name,handler);return()=>eventTarget.removeEventListener(name,handler)}},
    sharedState:{get:key=>shared.get(key)as never,subscribe:()=>()=>{}},theme:{locale,direction:direction(locale)}};
}
function LegacyHost({remote,runtime,manifest}:{remote:Extract<RemoteModule,{contractVersion:'1'}>;runtime:HostRuntime;manifest:EffectiveManifest}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>ref.current?remote.mount(ref.current,{locale:runtime.theme.locale,manifest,correlationId:()=>crypto.randomUUID()}):undefined,[remote,runtime,manifest]);return <div ref={ref}/>}
function RemotePluginHost({module,manifest,locale,currentUser}:{module:UiModuleDefinition;manifest:EffectiveManifest;locale:Locale;currentUser:CurrentUser|null}){
  const navigate=useNavigate(),runtime=useMemo(()=>createRuntime(module,navigate,locale,currentUser),[module,navigate,locale,currentUser]);const[remote,setRemote]=useState<LoadedRemoteModule>(),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
  useEffect(()=>{let active=true;setRemote(undefined);setError('');loadRemote(module.remote.remoteName,module.remote.remoteEntryUrl,module.remote.exposedModule,manifest.uiCatalog?.modules.map(x=>x.remote.remoteEntryUrl)??[],module.remote.integrity).then(value=>{if(active)setRemote(value)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:String(reason))});return()=>{active=false}},[module,manifest,attempt]);
  const retry=()=>{clearRemoteCache(module.remote.remoteName);setAttempt(v=>v+1)};if(error)return <Alert type="error" showIcon message={t(locale,'remoteUnavailable')} description={error} action={<Button onClick={retry}>تلاش مجدد</Button>}/>;if(!remote)return <Spin tip={t(locale,'loading')}/>;
  return <RemoteBoundary onRetry={retry}>{remote.contractVersion==='1.0'?<remote.App runtime={runtime} manifest={manifest}/>:<LegacyHost remote={remote} runtime={runtime} manifest={manifest}/>}</RemoteBoundary>;
}
function AuthorizedModuleHost({module,manifest,locale,currentUser}:{module:UiModuleDefinition;manifest:EffectiveManifest;locale:Locale;currentUser:CurrentUser|null}){
  const location=useLocation(),local=localModulePath(module,location.pathname);
  const route=authorizedCatalogRoute(module,location.pathname);
  if(!route&&local==='') {
    const fallback=module.routes.find(item=>item.id===module.defaultRouteId)??module.routes[0];
    if(fallback)return <Navigate replace to={composeModulePath(module,fallback.path)}/>;
  }
  if(!route)return <Alert type="error" showIcon message="403 — دسترسی به این مسیر مجاز نیست"/>;
  return <RemotePluginHost module={module} manifest={manifest} locale={locale} currentUser={currentUser}/>;
}
function Shell(){const[locale,setLocale]=useState<Locale>('fa-IR'),[manifest,setManifest]=useState<EffectiveManifest>(),[currentUser,setCurrentUser]=useState<CurrentUser|null>(null),[error,setError]=useState(''),[loggingOut,setLoggingOut]=useState(false);const location=useLocation(),navigate=useNavigate();
  const load=async(signal?:AbortSignal)=>{setError('');try{const context=await contextClient.get<EffectiveUserContext>('/api/me/context',{signal,headers:{'Cache-Control':'no-cache'}});authorization.setContext(context);setManifest(context);setCurrentUser({...context.identity,groups:[]})}catch(e){if(e instanceof DOMException&&e.name==='AbortError')return;if(e instanceof ApiError&&[0,302,401].includes(e.status)){window.location.assign('/oauth2/authorization/public-iam');return}setError(e instanceof Error?e.message:String(e))}};useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort()},[]);
  const logout=async()=>{setLoggingOut(true);try{await contextClient.request<void>('/auth/logout',{method:'POST'});authorization.clear();window.location.assign('/oauth2/authorization/public-iam')}catch(reason){setLoggingOut(false);message.error(reason instanceof Error?reason.message:'خروج از سامانه ناموفق بود')}};
  const modules=manifest?.uiCatalog?.modules??[];const active=activeCatalogModule(modules,location.pathname);const catalogItems=catalogMenuItems(modules),activeMenuKey=activeCatalogMenuKey(catalogItems,location.pathname);const renderMenu=(items:CatalogMenuItem[]):any[]=>items.map(item=>({key:item.key,label:item.description?<Tooltip placement="left" title={item.description}><span className="nav-menu-label">{item.title}</span></Tooltip>:item.title,icon:<span className="nav-icon">{item.icon??'•'}</span>,children:item.children?.length?renderMenu(item.children):undefined}));const menuItems=renderMenu(catalogMenuTree(catalogItems));
  const first=catalogItems.find(item=>item.type==='PAGE')?.key;return <ConfigProvider direction={direction(locale)} locale={locale==='fa-IR'?faIR:enUS} theme={{token:{colorPrimary:'#6d5dfc',borderRadius:12,fontFamily:'Tahoma, Arial, sans-serif'}}}><SHManifestProvider initial={manifest??empty}><Layout className="app-shell"><Layout.Header className="app-header"><div className="brand"><span className="brand-mark">A</span><Typography.Title level={3}>{t(locale,'appName')}</Typography.Title></div><Space><Tag color="green">Online</Tag>{currentUser&&<Tag>{currentUser.displayName??currentUser.username}</Tag>}<Button ghost onClick={()=>setLocale(locale==='fa-IR'?'en-US':'fa-IR')}>{t(locale,'language')}</Button><Button ghost loading={loggingOut} onClick={()=>void logout()}>خروج</Button></Space></Layout.Header><Layout><Layout.Sider className="app-sidebar" breakpoint="lg" collapsedWidth="0"><div className="nav-caption">فضاهای کاری</div><Menu mode="inline" selectedKeys={activeMenuKey?[activeMenuKey]:[]} onSelect={({key})=>{if(String(key).startsWith('https://'))window.location.assign(String(key));else if(!String(key).startsWith('group:'))navigate(String(key))}} items={menuItems}/></Layout.Sider><Layout.Content className="app-content"><div className="page-heading"><div><span className="eyebrow">AUREVIA / {active?.moduleKey??'HOME'}</span><Typography.Title level={2}>{active?(locale==='fa-IR'?active.displayName:active.displayNameEn):t(locale,'appName')}</Typography.Title></div><Space><Tag>{manifest?.uiCatalog?.catalogVersion??manifest?.version??'...'}</Tag><Button onClick={()=>void load()}>بازخوانی</Button></Space></div><main className="remote-surface">{error?<Alert showIcon type="error" message="خطا در بارگذاری" description={error} action={<Button onClick={()=>void load()}>تلاش مجدد</Button>}/>:!manifest?<Spin size="large"/>:<Routes><Route path="/login" element={<Navigate to="/oauth2/authorization/public-iam" replace/>}/>{modules.map(module=><Route key={module.registrationId} path={`/${module.routePrefix}/*`} element={<AuthorizedModuleHost module={module} manifest={manifest} locale={locale} currentUser={currentUser}/>}/>)}<Route path="/" element={first?<Navigate to={first} replace/>:<Typography.Title level={3}>هیچ میکروفرانت مجازی وجود ندارد</Typography.Title>}/><Route path="*" element={<Alert type="warning" showIcon message="مسیر یا میکروفرانت یافت نشد"/>}/></Routes>}</main></Layout.Content></Layout></Layout></SHManifestProvider></ConfigProvider>}
createRoot(document.getElementById('root')!).render(<BrowserRouter><Shell/></BrowserRouter>);
