import React,{Component,useEffect,useMemo,useRef,useState,type ReactNode}from'react';
import{createRoot}from'react-dom/client';import{Alert,Button,ConfigProvider,Layout,Menu,Space,Spin,Tag,Typography,message}from'antd';
import faIR from'antd/locale/fa_IR';import enUS from'antd/locale/en_US';import{BrowserRouter,Navigate,Route,Routes,useLocation,useNavigate}from'react-router-dom';
import type{EffectiveManifest,HostRuntime,LoadedRemoteModule,RemoteModule,Locale,UiModuleDefinition}from'@aurevia/contracts';
import{direction,t}from'@aurevia/i18n';import{SHManifestProvider}from'@aurevia/sh-core-ui';import{clearRemoteCache,loadRemote}from'./remote-loader';import'./styles.css';

const empty:EffectiveManifest={version:'none',expiresAt:new Date(Date.now()+60000).toISOString(),panels:[],permissions:{}};
class RemoteBoundary extends Component<{children:ReactNode;onRetry:()=>void},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?<Alert type="error" showIcon message="میکروفرانت دچار خطا شد" action={<Button onClick={()=>{this.setState({failed:false});this.props.onRetry()}}>تلاش مجدد</Button>}/>:this.props.children}}
const eventTarget=new EventTarget(),shared=new Map<string,unknown>();
let csrf:Promise<{headerName:string;token:string}>|undefined;
async function jsonRequest<T>(base:string,path:string,init:RequestInit={}):Promise<T>{const normalized=`/${path}`.replace(/\/+/g,'/'),headers:Record<string,string>={'Content-Type':'application/json','X-Correlation-ID':crypto.randomUUID(),...(init.headers as Record<string,string>)};if(init.method&& !['GET','HEAD'].includes(init.method)){csrf??=fetch('/api/v1/csrf',{credentials:'same-origin'}).then(async r=>{if(!r.ok)throw new Error(`CSRF HTTP ${r.status}`);return r.json()});const token=await csrf;headers[token.headerName]=token.token}const response=await fetch(`${base}${normalized}`,{...init,credentials:'same-origin',headers});if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.json()as Promise<T>}
function createRuntime(module:UiModuleDefinition,navigate:ReturnType<typeof useNavigate>,locale:Locale):HostRuntime{
  const base=`/${module.routePrefix}`;return{mode:'embedded',moduleKey:module.moduleKey,routePrefix:module.routePrefix,
    http:{get:(p,o)=>jsonRequest(module.runtime.apiBasePath,p,{headers:o?.headers,signal:o?.signal}),post:(p,b,o)=>jsonRequest(module.runtime.apiBasePath,p,{method:'POST',body:JSON.stringify(b),headers:o?.headers,signal:o?.signal}),put:(p,b,o)=>jsonRequest(module.runtime.apiBasePath,p,{method:'PUT',body:JSON.stringify(b),headers:o?.headers,signal:o?.signal})},
    navigation:{navigate:p=>navigate(`${base}/${p}`.replace(/\/+/g,'/')),getModuleBasePath:()=>base},session:{getCurrentUser:()=>null,subscribe:()=>()=>{}},notifications:{success:m=>message.success(m),error:m=>message.error(m)},
    events:{emit:(name,payload)=>eventTarget.dispatchEvent(new CustomEvent(name,{detail:payload})),subscribe:(name,listener)=>{const handler=(event:Event)=>listener((event as CustomEvent).detail);eventTarget.addEventListener(name,handler);return()=>eventTarget.removeEventListener(name,handler)}},
    sharedState:{get:key=>shared.get(key)as never,subscribe:()=>()=>{}},theme:{locale,direction:direction(locale)}};
}
function LegacyHost({remote,runtime,manifest}:{remote:Extract<RemoteModule,{contractVersion:'1'}>;runtime:HostRuntime;manifest:EffectiveManifest}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>ref.current?remote.mount(ref.current,{locale:runtime.theme.locale,manifest,correlationId:()=>crypto.randomUUID()}):undefined,[remote,runtime,manifest]);return <div ref={ref}/>}
function RemotePluginHost({module,manifest,locale}:{module:UiModuleDefinition;manifest:EffectiveManifest;locale:Locale}){
  const navigate=useNavigate(),runtime=useMemo(()=>createRuntime(module,navigate,locale),[module,navigate,locale]);const[remote,setRemote]=useState<LoadedRemoteModule>(),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
  useEffect(()=>{let active=true;setRemote(undefined);setError('');loadRemote(module.remote.remoteName,module.remote.remoteEntryUrl,module.remote.exposedModule,manifest.uiCatalog?.modules.map(x=>x.remote.remoteEntryUrl)??[],module.remote.integrity).then(value=>{if(active)setRemote(value)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:String(reason))});return()=>{active=false}},[module,manifest,attempt]);
  const retry=()=>{clearRemoteCache(module.remote.remoteName);setAttempt(v=>v+1)};if(error)return <Alert type="error" showIcon message={t(locale,'remoteUnavailable')} description={error} action={<Button onClick={retry}>تلاش مجدد</Button>}/>;if(!remote)return <Spin tip={t(locale,'loading')}/>;
  return <RemoteBoundary onRetry={retry}>{remote.contractVersion==='1.0'?<remote.App runtime={runtime} manifest={manifest}/>:<LegacyHost remote={remote} runtime={runtime} manifest={manifest}/>}</RemoteBoundary>;
}
function Shell(){const[locale,setLocale]=useState<Locale>('fa-IR'),[manifest,setManifest]=useState<EffectiveManifest>(),[error,setError]=useState('');const location=useLocation(),navigate=useNavigate();
  const load=()=>{const controller=new AbortController();setError('');fetch('/api/v1/me/manifest',{credentials:'same-origin',redirect:'manual',signal:controller.signal,headers:{'X-Correlation-ID':crypto.randomUUID()}}).then(r=>{if(r.status===401||r.status===302||r.type==='opaqueredirect'){window.location.assign('/oauth2/authorization/public-iam');throw new Error('AUTH_REDIRECT')}if(!r.ok)throw new Error(String(r.status));return r.json()}).then(setManifest).catch(e=>{if(!(e instanceof Error&&(e.message==='AUTH_REDIRECT'||e.name==='AbortError')))setError(e instanceof Error?e.message:String(e))});return()=>controller.abort()};useEffect(load,[]);
  const modules=manifest?.uiCatalog?.modules??[];const active=modules.find(m=>location.pathname===`/${m.routePrefix}`||location.pathname.startsWith(`/${m.routePrefix}/`));const menuItems=modules.flatMap(module=>module.menus.map(item=>({key:`/${module.routePrefix}/${module.routes.find(r=>r.id===item.routeId)?.path??''}`.replace(/\/$/,''),label:item.title,icon:<span className="nav-icon">{item.icon??module.icon??'•'}</span>})));
  const first=menuItems[0]?.key;return <ConfigProvider direction={direction(locale)} locale={locale==='fa-IR'?faIR:enUS} theme={{token:{colorPrimary:'#6d5dfc',borderRadius:12,fontFamily:'Tahoma, Arial, sans-serif'}}}><SHManifestProvider initial={manifest??empty}><Layout className="app-shell"><Layout.Header className="app-header"><div className="brand"><span className="brand-mark">A</span><Typography.Title level={3}>{t(locale,'appName')}</Typography.Title></div><Space><Tag color="green">Online</Tag><Button ghost onClick={()=>setLocale(locale==='fa-IR'?'en-US':'fa-IR')}>{t(locale,'language')}</Button><Button ghost href="/auth/logout">خروج</Button></Space></Layout.Header><Layout><Layout.Sider className="app-sidebar" breakpoint="lg" collapsedWidth="0"><div className="nav-caption">فضاهای کاری</div><Menu mode="inline" selectedKeys={[location.pathname]} onSelect={({key})=>navigate(key)} items={menuItems}/></Layout.Sider><Layout.Content className="app-content"><div className="page-heading"><div><span className="eyebrow">AUREVIA / {active?.moduleKey??'HOME'}</span><Typography.Title level={2}>{active?(locale==='fa-IR'?active.displayName:active.displayNameEn):t(locale,'appName')}</Typography.Title></div><Space><Tag>{manifest?.uiCatalog?.catalogVersion??manifest?.version??'...'}</Tag><Button onClick={load}>بازخوانی</Button></Space></div><main className="remote-surface">{error?<Alert showIcon type="error" message="خطا در بارگذاری" description={error} action={<Button onClick={load}>تلاش مجدد</Button>}/>:!manifest?<Spin size="large"/>:<Routes><Route path="/login" element={<Navigate to="/oauth2/authorization/public-iam" replace/>}/>{modules.map(module=><Route key={module.registrationId} path={`/${module.routePrefix}/*`} element={<RemotePluginHost module={module} manifest={manifest} locale={locale}/>}/>)}<Route path="/" element={first?<Navigate to={first} replace/>:<Typography.Title level={3}>هیچ میکروفرانت مجازی وجود ندارد</Typography.Title>}/><Route path="*" element={<Alert type="warning" showIcon message="مسیر یا میکروفرانت یافت نشد"/>}/></Routes>}</main></Layout.Content></Layout></Layout></SHManifestProvider></ConfigProvider>}
createRoot(document.getElementById('root')!).render(<BrowserRouter><Shell/></BrowserRouter>);
