import os

SECRET_KEY = os.environ["SUPERSET_SECRET_KEY"]
SQLALCHEMY_DATABASE_URI = os.environ["SUPERSET_DATABASE_URI"]
SESSION_COOKIE_NAME = "AUREVIA_OPERATION_SUPERSET"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = os.getenv("SUPERSET_COOKIE_SECURE", "false").lower() == "true"
PUBLIC_ROLE_LIKE = None
FEATURE_FLAGS = {"ENABLE_VIEWERS": False}
ENABLE_PROXY_FIX = True
TALISMAN_ENABLED = False
