import os
SECRET_KEY = os.environ["SUPERSET_SECRET_KEY"]
SESSION_COOKIE_NAME = "AUREVIA_OPERATION_SUPERSET"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
PUBLIC_ROLE_LIKE = None
FEATURE_FLAGS = {"ENABLE_VIEWERS": False}
